create database ZomatoDB;
use ZomatoDB;

CREATE TABLE Zomato_Restaurants (
    restaurant_id INT PRIMARY KEY,
    restaurant_name VARCHAR(255),
    city VARCHAR(100),
    area VARCHAR(100),
    cuisine VARCHAR(255),
    avg_rating DECIMAL(3,2),
    total_ratings INT,
    price_range VARCHAR(20),
    delivery_available VARCHAR(10)
);

CREATE TABLE Zomato_Orders (
    order_id INT PRIMARY KEY,
    restaurant_id INT,
    customer_id INT,
    order_date DATE,
    order_time TIME,
    delivery_time INT,
    total_cost DECIMAL(10,2),
    item_count INT,
    payment_method VARCHAR(50),
    customer_rating DECIMAL(2,1),
    FOREIGN KEY (restaurant_id) REFERENCES Zomato_Restaurants(restaurant_id)
);

DROP TABLE Zomato_Orders;

DROP TABLE Zomato_Restaurants;

CREATE TABLE Zomato_Restaurants (
    restaurant_id VARCHAR(50) PRIMARY KEY,
    restaurant_name VARCHAR(255),
    city VARCHAR(100),
    area VARCHAR(100),
    cuisine VARCHAR(255),
    avg_rating DECIMAL(3,2),
    total_ratings INT,
    price_range VARCHAR(20),
    delivery_available VARCHAR(10)
);

CREATE TABLE Zomato_Orders (
    order_id VARCHAR(50) PRIMARY KEY,
    restaurant_id VARCHAR(50),
    customer_id INT,
    order_date DATE,
    order_time TIME,
    delivery_time INT,
    total_cost DECIMAL(10,2),
    item_count INT,
    payment_method VARCHAR(50),
    customer_rating DECIMAL(2,1),
    FOREIGN KEY (restaurant_id) REFERENCES Zomato_Restaurants(restaurant_id)
);

select* from zomato_orders;

select * from zomato_restaurants;

checking duplicates;

SELECT order_id, COUNT(*) AS duplicate_count
FROM zomato_orders
GROUP BY order_id
HAVING COUNT(*) > 1;

SELECT restaurant_id, COUNT(*) AS duplicate_count
FROM zomato_restaurants
GROUP BY restaurant_id
HAVING COUNT(*) > 1;

handling null values;

SELECT *
FROM zomato_orders
WHERE order_id IS NULL
   OR restaurant_id IS NULL
   OR customer_id IS NULL
   OR order_date IS NULL
   OR order_time IS NULL
   OR delivery_time IS NULL
   OR total_cost IS NULL
   OR item_count IS NULL
   OR payment_method IS NULL
   OR customer_rating IS NULL;
   
   SELECT *
FROM zomato_restaurants
WHERE restaurant_id IS NULL
   OR restaurant_name IS NULL
   OR city IS NULL
   OR area IS NULL
   OR cuisine IS NULL
   OR avg_rating IS NULL
   OR total_ratings IS NULL
   OR price_range IS NULL
   OR delivery_available IS NULL;
   
   Data Exploration Queries;
   
   no of restaurants in each city;
   
   SELECT city, COUNT(*) AS total_restaurants
FROM zomato_restaurants
GROUP BY city;

top 5 cities with highest number of orders;

SELECT r.city,
       COUNT(o.order_id) AS total_orders
FROM zomato_orders o
JOIN zomato_restaurants r
ON o.restaurant_id = r.restaurant_id
GROUP BY r.city
ORDER BY total_orders DESC
LIMIT 5;

total revenue generated by each restaurant;

SELECT r.restaurant_name,
       SUM(o.total_cost) AS total_revenue
FROM zomato_orders o
JOIN zomato_restaurants r
ON o.restaurant_id = r.restaurant_id
GROUP BY r.restaurant_name
ORDER BY total_revenue DESC;

average order amount for each city;

SELECT r.city,
       AVG(o.total_cost) AS average_order_amount
FROM zomato_orders o
JOIN zomato_restaurants r
ON o.restaurant_id = r.restaurant_id
GROUP BY r.city;

top 5 restaurants with the highest total sales;

SELECT r.restaurant_name,
       SUM(o.total_cost) AS total_sales
FROM zomato_orders o
JOIN zomato_restaurants r
ON o.restaurant_id = r.restaurant_id
GROUP BY r.restaurant_name
ORDER BY total_sales DESC
LIMIT 5;

Joining the tables to get restaurant names along with order details;

SELECT o.order_id,
       r.restaurant_name,
       r.city,
       o.customer_id,
       o.order_date,
       o.order_time,
       o.total_cost,
       o.item_count,
       o.payment_method,
       o.customer_rating
FROM zomato_orders o
JOIN zomato_restaurants r
ON o.restaurant_id = r.restaurant_id;



